### ISSUE TITLE
Surface the entity resolution method in the output of the base module

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/STAT-Function#100]
It would be useful for troubleshooting to know how the entity was "enriched" in the base module. Like was it using the UPN, the SID, the ObjectID, the sAMAccountName... That would allow us to determine how confident we are with the entity we have enriched (sAMAccountName can be duplicated, or mismatched between local account not synched and synched users - ie. local built-in administrator being wrongly enriched as a synced domain administrator).

**Comment by briandelmsft** [comment]
@piaudonn Where do you think we should put it?  I think we need to go into the accounts array as there could be more than one and they could take different enrichment paths.

I can see this being useful mainly in 2 cases, the entity gets resolved incorrectly (like 2 accounts with the same samaccountname in different domains) or the entity doesn't get resolved at all and you want to know what path it took and failed on.

So in some cases we'll have a fully enriched entity it's just wrong and in other cases we'll have only the original input entity data which we currently return like this:

```json
{
      "RawEntity": {
        "accountName": "bob",
        "ntDomain": "ad",
        "upnSuffix": "contoso.com",
        "friendlyName": "bob@contoso.com"
      }
    }
```

So do you think we would return it something like this:

```json
{
      "EnrichmentType": "UPN",
      "RawEntity": {
        "accountName": "bob",
        "ntDomain": "ad",
        "upnSuffix": "contoso.com",
        "friendlyName": "bob@contoso.com"
      }
    }
```
Or do you have something else in mind?
