### ISSUE TITLE
MDCA Investigation Priority Score Retirement

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/STAT-Function#106]
The investigation priority score is retiring, published in message center under MC889532, it is expected to be fully decommissioned by the end of November.  This effectively renders the MDCA module inoperable.

Tenants where this has been decommissioned and are using the MDCA module will start to see an error like this:

```json
{
    "Error": "Module processing failed, an unknown exception has occurred.",
    "InvocationId": "170d5892-08cd-4c18-9e2b-5aaf263fa877",
    "Traceback": [
        "Traceback (most recent call last):\n",
        "  File \"/home/site/wwwroot/modules/__init__.py\", line 19, in main\n    return_data = coordinator.initiate_module(module_name=module_name, req_body=req_body)\n",
        "  File \"/home/site/wwwroot/shared/coordinator.py\", line 21, in initiate_module\n    return_data = mdca.execute_mdca_module(req_body)\n",
        "  File \"/home/site/wwwroot/modules/mdca.py\", line 50, in execute_mdca_module\n    current_account['ThreatScore'] = 0 if mdcaresults['threatScore'] is None else mdcaresults['threatScore']\n",
        "KeyError: 'threatScore'\n"
    ]
}
```

So we likely need to retire the module but would like to do so in a way that won't create much impact for anyone who is calling it.  I propose we:

- [x] Add a section to the FAQ in the Wiki
- [x] Change the module to always return successfully with minimal payload, adding a comment to the incident that they are using a deprecated module, include enough so the scoring module won't fail
- [x] Hide the MDCA action in the custom connector so it won't break existing deployments, but you won't be able to add it in new
- [x] Add warning to the scoring module if MDCA module is passed
- [x] Remove from test cases

@piaudonn am I missing anything?  Or in the alternative, is there another investment we should make into the module to save it?

**Comment by piaudonn** [comment]
I feel like this is the end for our integration...

**Comment by briandelmsft** [comment]
@piaudonn yeah I think so too, I don't see anywhere else to go with it.  Do you agree with the steps I've listed in original post or do you think I'm missing anything that we need/should do?

**Comment by briandelmsft** [comment]
@piaudonn I don't see any reason to keep it
