### ISSUE TITLE
Migrate Run Playbook Module to GA API when available

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/STAT-Function#32]
The Run Playbook module uses a preview api `/runPlaybook?api-version=2022-07-01-preview` however no GA version is available at this time.

**Comment by piaudonn** [comment]
`2024-03-01` is now available https://learn.microsoft.com/en-us/rest/api/securityinsights/entities/run-playbook?view=rest-securityinsights-2024-03-01&tabs=HTTP
