### ISSUE TITLE
Scoring Update - MDCA Enhancements

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/STAT-Function#46]
Scoring module update for MDCA module enhancements.

Look to include top risky users and trending up users in score calculation

**Comment by briandelmsft** [comment]
@piaudonn thoughts on this and logic for it?
Current logic when scoring per item - UsersAboveThreshold * 10 * Multiplier
Current logic when not scoring per item - If AboveThresholdCount > 0, 10 * Multiplier

Thinking of keeping the above logic plus:
+ 10 for user being TopUserThresholdCount
+ 5 for ThreatScoreTrendingUp

**Comment by piaudonn** [comment]
@briandelmsft  that looks fine yes :)
