### ISSUE TITLE
[BUG] Base Module - AddAccountComments parameter is ignored

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/STAT-Function#65]
Typo in the code, we check for the parameter `AddAccountComment` instead of `AddAccountComments`. As a result, we always add comments for Accounts.
https://github.com/briandelmsft/STAT-Function/blob/main/modules/base.py#L61

Need to check for the other comment parameters if it needs to be plural or not.

**Comment by briandelmsft** [comment]
looks like this is probably true for the IP comment too based on the connector:

https://github.com/briandelmsft/SentinelAutomationModules/blob/ca36f641e7401cc8dcc9cc77f6eac57f0f16ff87/Connector/connector.json#L110
